### Import all required libraries

In [34]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import random
import math
from pprint import pprint

### Training and testing data preprocessing is done together

### Load dataset (training and testing data)

In [35]:
# Load dataset
train_df = pd.read_csv("customer_churn_dataset-training-master.csv")

print(train_df)

        CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0              2.0  30.0  Female    39.0             14.0            5.0
1              3.0  65.0  Female    49.0              1.0           10.0
2              4.0  55.0  Female    14.0              4.0            6.0
3              5.0  58.0    Male    38.0             21.0            7.0
4              6.0  23.0    Male    32.0             20.0            5.0
...            ...   ...     ...     ...              ...            ...
440828    449995.0  42.0    Male    54.0             15.0            1.0
440829    449996.0  25.0  Female     8.0             13.0            1.0
440830    449997.0  26.0    Male    35.0             27.0            1.0
440831    449998.0  28.0    Male    55.0             14.0            2.0
440832    449999.0  31.0    Male    48.0             20.0            1.0

        Payment Delay Subscription Type Contract Length  Total Spend  \
0                18.0          Standard          Annual       932.00
1                 8.0             Basic         Monthly       557.00
2                18.0             Basic       Quarterly       185.00
3                 7.0          Standard         Monthly       396.00
4                 8.0             Basic         Monthly       617.00
...               ...               ...             ...          ...
440828            3.0           Premium          Annual       716.38
440829           20.0           Premium          Annual       745.38
440830            5.0          Standard       Quarterly       977.31
440831            0.0          Standard       Quarterly       602.55
440832           14.0           Premium       Quarterly       567.77

        Last Interaction  Churn
0                   17.0    1.0
1                    6.0    1.0
2                    3.0    1.0
3                   29.0    1.0
4                   20.0    1.0
...                  ...    ...
440828               8.0    0.0
440829               2.0    0.0
440830               9.0    0.0
440831               2.0    0.0
440832              21.0    0.0

[440833 rows x 12 columns]

Explanation:  
== The code ==  
Load dataset by importing pandas and math library is used to calculate entropy.  
We load dataset by reading csv using pandas. Therefore, the data can be used for next steps.  

== The outcome ==  
No outcome is shown. However, the original dataset is read and train_df created for the following steps.

### Load test data

In [36]:
# Load dataset
test_df = pd.read_csv("customer_churn_dataset-testing-master.csv")

Explanation:  
== The code ==  
Load test data to test the decision tree model.  

== The outcome ==  
No outcome is shown. However the test data is prepared for further usage.

In [37]:
train_df.head(15)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0
5,8.0,51.0,Male,33.0,25.0,9.0,26.0,Premium,Annual,129.0,8.0,1.0
6,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.0,24.0,1.0
7,10.0,55.0,Female,37.0,8.0,4.0,15.0,Premium,Annual,445.0,30.0,1.0
8,11.0,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.0,13.0,1.0
9,12.0,64.0,Female,3.0,25.0,2.0,11.0,Standard,Quarterly,415.0,29.0,1.0
10,13.0,29.0,Male,18.0,9.0,0.0,30.0,Premium,Quarterly,930.0,18.0,1.0
11,14.0,52.0,Female,21.0,6.0,3.0,26.0,Premium,Monthly,830.0,19.0,1.0
12,15.0,22.0,Male,41.0,17.0,10.0,25.0,Basic,Quarterly,265.0,23.0,1.0
13,16.0,48.0,Female,35.0,25.0,1.0,13.0,Basic,Annual,518.0,17.0,1.0
14,17.0,24.0,Male,4.0,9.0,4.0,22.0,Standard,Quarterly,204.0,4.0,1.0

In [38]:
test_df.head(15)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0
5,6,30,Male,41,14,10,10,Premium,Monthly,500,29,0
6,7,47,Female,37,15,9,28,Basic,Quarterly,574,14,1
7,8,54,Female,36,11,0,18,Standard,Monthly,323,16,0
8,9,36,Male,20,5,10,8,Basic,Monthly,687,8,0
9,10,65,Male,8,4,2,23,Basic,Annual,995,10,0
10,11,46,Female,42,27,9,21,Standard,Annual,526,3,1
11,12,56,Male,13,23,5,14,Basic,Quarterly,187,1,0
12,13,31,Male,2,7,0,25,Premium,Quarterly,758,24,0
13,14,42,Male,46,27,5,8,Premium,Quarterly,438,30,0
14,15,59,Male,21,17,2,14,Premium,Quarterly,663,15,0

Explanation:  
Use head() to show the data row-by-row. Number inside head() is the number of line we need.

In [39]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [40]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

Explanation:  
info() shows us the attribute lists with their corresponding data types.

### Drop unpredictive columns

In [41]:
# Drop ID column
train_df.drop(columns="CustomerID", inplace=True)

# Copy the target churn to compare with training data
train_label = train_df["Churn"].copy()

In [42]:
# Drop ID column
test_df.drop(columns="CustomerID", inplace=True)

# Copy the target churn to compare with test data
test_label = test_df["Churn"].copy()

Explanation:  
== The code ==  
CustomerID is a unique identifier for each customer. It does not contain any behavioural patterns related to our classification. Therefore, it is removed to avoid introducing noise into the model.  
test_label copy the target column to serve as answer when compare with the test set.

### Identify the missing values for training data

In [43]:
# Check missing values per column
missing_values = train_df.isnull().sum()

# Print the missing values if it is available
print(missing_values)

Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

Explanation:  
== The code ==  
Find the missing values by using isnull() in train_df training data, sum() to accumulate the number of value.  

== The outcome ==  
This shows how many missing values each attribute has. It will show a list of attributes with their missing values respectively.

### Propose a method to clean the missing values.

In [44]:
# Fill numerical columns with median
# Choose the numerical columns from training data
num_cols = train_df.select_dtypes(include="number").columns
# Fill in the columns with median
train_df[num_cols] = train_df[num_cols].fillna(train_df[num_cols].median())

# Fill categorical columns with mode
# Choose the categorical columns from training data
cat_cols = train_df.select_dtypes(include="object").columns
# Fill in the columns with mode
for col in cat_cols:
  train_df[col].fillna(train_df[col].mode()[0], inplace=True)

/tmp/ipython-input-2412417230.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[col].fillna(train_df[col].mode()[0], inplace=True)

Explanation:  
== The code ==  
num_cols = train_df.select_dtypes(include="number").columns means:  
from train_df, select numerical columns, and define it as num_cols.  

train_df[num_cols] = train_df[num_cols].fillna(train_df[num_cols].median())  
For each key (numerical column) in train_df, fillna means replaces NaN values, .median() means replace the missing columns with median, but all non-missing values remain unchanged.  

cat_cols = train_df.select_dtypes(include="object").columns means:  
from train_df, select categorical columns, and define it as cat_cols.  

for col in cat_cols:  
train_df[col].fillna(train_df[col].mode()[0], inplace=True)  
for each columns, fill up those NaN columns with mode().  

We use median for numerical columns as it is robust to outliers, while mode preserves categorical meaning. Thus, we can continue to train our model with the training data instead of delete them. This approach helps preserve dataset size while minimizing distortion to the original data distribution.    

== The outcome ==  
No outcome is shown. However, the missing values are replaced for further training.

### Check for missing data after data cleaning.

In [45]:
# Check missing values per column
missing_values = train_df.isnull().sum()

# Print the missing values if it is available
print(missing_values)

Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

No missing value left.

### Identify missing values for testing data

In [46]:
# Check missing values per column
missing_values = test_df.isnull().sum()

# Print the missing values if it is available
print(missing_values)

Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

Explanation:  
== The code ==  
Find the missing values by using isnull() in test_df testing data, sum() to accumulate the number of value.  

== The outcome ==  
This shows how many missing values each attribute has. It will show a list of attributes with their missing values respectively. Since our result shows 0 for all attributes, there is no missing value.

### (1) Use binning to transform continuous attributes (if any) into discrete values.

"Age", "Tenure", "Usage Frequency", "Support Calls", "Payment Delay", "Total Spend", "Last Interaction"  
We have 7 attributes for binning

Explanation:  
Why we need to use binning?  
Decision trees work naturally with categorical attributes. Binning continuous attributes simplifies entropy calculation and ensures compatibility with a categorical decision tree implementation. We need to use it to transform continuous attributes into discrete values.

In [47]:
# Set the labels for each bin
age_labels = ["age_1", "age_2", "age_3", "age_4", "age_5"]

# Define an attribute for the bins
train_df["Age_Bin"] = pd.qcut(train_df["Age"], q=5, precision=1, labels=age_labels)

In [48]:
# Set the labels for each bin
tenure_labels = ["tenure_1", "tenure_2", "tenure_3", "tenure_4", "tenure_5"]

# Define an attribute for the bins
train_df["Tenure_Bin"] = pd.qcut(train_df["Tenure"], q=5, precision=1, labels=tenure_labels)

In [49]:
# Set the labels for each bin
uf_labels = ["uf_1", "uf_2", "uf_3", "uf_4", "uf_5"]

# Define an attribute for the bins
train_df["Usage Frequency_Bin"] = pd.qcut(train_df["Usage Frequency"], q=5, precision=1, labels=uf_labels)

In [50]:
# Set the labels for each bin
sc_labels = ["sc_1", "sc_2", "sc_3", "sc_4", "sc_5"]

# Define an attribute for the bins
train_df["Support Calls_Bin"] = pd.qcut(train_df["Support Calls"], q=5, precision=1, labels=sc_labels)

In [51]:
# Set the labels for each bin
pd_labels = ["pd_1", "pd_2", "pd_3", "pd_4", "pd_5"]

# Define an attribute for the bins
train_df["Payment Delay_Bin"] = pd.qcut(train_df["Payment Delay"], q=5, precision=1, labels=pd_labels)

In [52]:
# Set the labels for each bin
spend_labels = ["Very Low", "Low", "Medium", "High", "Very High"]

# Define an attribute for the bins
train_df["TotalSpend_Bin"] = pd.qcut(train_df["Total Spend"], q=5, precision=1, labels=spend_labels)

In [53]:
# Set the labels for each bin
li_labels = ["li_1", "li_2", "li_3", "li_4", "li_5"]

# Define an attribute for the bins
train_df["Last Interaction_Bin"] = pd.qcut(train_df["Last Interaction"], q=5, precision=1, labels=li_labels)

In [54]:
# Drop the attributes
train_df.drop(columns=["Age", "Tenure", "Usage Frequency", "Support Calls", "Payment Delay", "Total Spend", "Last Interaction"], inplace=True)

In [55]:
# Show all existing attributes
print(train_df.columns)

Index(['Gender', 'Subscription Type', 'Contract Length', 'Churn', 'Age_Bin',
       'Tenure_Bin', 'Usage Frequency_Bin', 'Support Calls_Bin',
       'Payment Delay_Bin', 'TotalSpend_Bin', 'Last Interaction_Bin'],
      dtype='object')

Explanation:  
As required, we need to transform continuous values to discrete values by binning.    
We use the pd.qcut() function, which performs Equal-Frequency Binning. Unlike standard binning that splits by range (width), qcut ensures that approximately the same number of customers falls into each of the 5 bins.  

== The code ==  
First, we set labels for each attribute that needs to be binned.   
We have 7 attributes need to be binned, so we define a new attribute as key (using attribute_Bin).  
Then, we use qcut(), and put the train_df["attribute"] inside to start the binning. q = 5 means we have 5 bins. Precision = 1 means it sets the number of decimal points for the bin labels be 1 decimal place, and the labels should put the target labels we set above, making the tree more readable.    

== The outcome ==  
Those original attributes will be dropped and replaced by "attribute"_bin. Each binned attributes are split to 5 bins.

In [56]:
# Set the labels for each bin
# Define an attribute for the bins
test_df["Age_Bin"] = pd.qcut(test_df["Age"], q=5, precision=1, labels=age_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["Tenure_Bin"] = pd.qcut(test_df["Tenure"], q=5, precision=1, labels=tenure_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["Usage Frequency_Bin"] = pd.qcut(test_df["Usage Frequency"], q=5, precision=1, labels=uf_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["Support Calls_Bin"] = pd.qcut(test_df["Support Calls"], q=5, precision=1, labels=sc_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["Payment Delay_Bin"] = pd.qcut(test_df["Payment Delay"], q=5, precision=1, labels=pd_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["TotalSpend_Bin"] = pd.qcut(test_df["Total Spend"], q=5, precision=1, labels=spend_labels)

# Set the labels for each bin
# Define an attribute for the bins
test_df["Last Interaction_Bin"] = pd.qcut(test_df["Last Interaction"], q=5, precision=1, labels=li_labels)

# Drop the attributes
test_df.drop(columns=["Age", "Tenure", "Usage Frequency", "Support Calls", "Payment Delay", "Total Spend", "Last Interaction"], inplace=True)

We apply the same binning strategy with training data to ensure that the features match to the training set.

### (2) It is recommended that your implementation includes a “tree induction function” and a “classification function”.

### 2.1 Entropy

In [57]:
from math import log
import operator

# Calculate the entropy of the target attribute
def entropy(data, target_column):

    # Get the target column
    target = target_column

    # Count each class, how many of the target
    counts = data[target].value_counts()

    # The original total value
    total = len(data)

    # Define ent as 0 to change it later
    ent = 0

    # For each count,
    for count in counts:

      # Calculate the probability by dividing the count with total value.
      p = count / total

      # Use the formula log base 2
      # The negative sign (-=) is used because logging a fraction (probability)
      # results in a negative number, and we want a positive entropy value.
      ent -= p * math.log2(p)

    return ent

Explanation:  
== The code ==  
In the code, we calculate how many instances exist the target. For example in the question, we calculate how many "Yes" / 1 in the customer_churn. total = len(data) shows the total number of the data. For each count, we use count divided by total to calculate the probability to be used in calculating entropy. ent -= p * math.log2(p) is entropy formula to calculate the final result. Lastly, we return the final entropy.  
Entropy is the measure of uncertainty. In the decision tree, we need to split the data in a way that makes the result as "pure" as possible, means that we prefer less uncertainty and most data points belong to the same class.  
In the return result, if the ent is 0, it is pure and it is good result. If it is 0.5, some of the data are mixed. If the entropy value is 1, it is completely mixed.
We need to calculate entropy because it is useful in Decision Tree, it is a good measurement to help us to choose splits that reduce entropy.

== The outcome ==  
No outcome is shown. The entropy function is used to create the decision tree.

### 2.2 Information Gain

In [58]:
# Calculate the information gain
def information_gain(data, attribute, target_column):

    # Calculate the total entropy, it shows how the target is mixed before splitting
    total_entropy = entropy(data, target_column)

    # Initialise weighted_entropy
    weighted_entropy = 0

    # For each value of the chosen data
    for value in data[attribute].unique():

      # Create a subset where the attribute equals the current value
      subset = data[data[attribute] == value]

      # Calculate the weight
      weight = len(subset) / len(data)

      # Calculate the average entropy after splitting
      weighted_entropy += weight * entropy(subset, target_column)

    # Return the information gain
    # Information gain is the reduction in entropy
    return total_entropy - weighted_entropy

Explanation:  
== The code ==  
In the code, we calculate the entropy of the whole dataset. This tells us the uncertainty before splitting.   
Next, we initialise the weighted entropy as 0, the variable will store the entropy after splitting.   
for value in data[attribute].unique():, for each attribute, we don't repeat same value by using unique(). With this function, we can calculate entropy for each unique value. subset = data[data[attribute] == value] select rows where the attribute equals the value as subset. For example, all rows where Gender = Male form a subset. By dividing the length of subset (len(subset)) with total length (len(data)), we can get the weight. Then, we update the weighted_entropy by multiply the entropy of the subset and its weight. The weighted_entropy is the after split entropy.   
Lastly, return total_entropy (before split entropy) - weighted_entropy (after split entropy) to get the information gain.  
We need to use information gain as it helps us choose the best attribute to split and chooses the split that reduces uncertainty the most. Therefore, it can helps the decision tree to build a cleaner and more accurate tree.  

== The outcome ==  
No outcome is shown. The information_gain function is used to create the decision tree.

### 2.3 Choose the best split

In [59]:
# This function is used to choose the best attribute
def best_attribute(data, attributes, target_column):

    # Initialise an empty dictionary as gains to make comparison
    gains = {}

    # For each attribute given,
    for att in attributes:

      # Calculate its information gain
      gains[att] = information_gain(data, att, target_column)

    # Return the attribute with highest information gain
    return max(gains, key=gains.get)

Explanation:  
== The code ==  
This function is designed to identify the attribute that provides the best split for the dataset. Splitting is choosing one attribute and dividing the data based on its value, it is how a decision tree "ask questions" to reduce uncertainty, because all data is mixed together at the start, we need to use decision tree to split it. For example, gender has "Male" and "Female". We can split the attribute gender so we have two branches "Male" and "Female". After splitting, each group becomes more similar internally and the target label becomes more predictable. Continue to do splitting with other attributes to get the class (the result).   

To create a decision tree, we need to choose a best split. Best split is defined as the splitting that is low uncertainty. For instance one group mostly "Yes" and another group mostly "No", but not letting data mix together. By coding, we can define best split as the attribute with the highest Information Gain. As high Information Gain means that big reduction in entropy, the larger the difference (1 group 90%, another group 10%) shows the purer groups, therefore better predictions.   
The function starts from defining an empty dictionary. Then for each attribute, calculate their information gain and put into the dictionary. Lastly, return the maximum information gain within the gains dictionary. The returned attribute is the best split.  

== The outcome ==  
No outcome is shown. The best_attribute function is used to choose the best element to split in creating the decision tree.

### 2.4 Tree induction function

In [60]:
def tree_induction(data, attributes, target_column, min_samples=200):

    # If all instances have same class,
    # cannot split further as no uncertainty left.
    if len(data[target_column].unique()) == 1:

      # If every row have the same label, return the first leaf node.
      return data[target_column].iloc[0]

    # Pre-pruning: stop if data too small
    # Cannot split further and must make decision
    if len(attributes) == 0 or len(data) < min_samples:

      # It will return the majority class (mode())
      return data[target_column].mode()[0]

    # Choose the best split by using the best_attribute function
    # created before
    best = best_attribute(data, attributes, target_column)

    # Create a dictionary to represent the node
    # Key: best attribute calculated above
    # Value: used to hold branches
    tree = {best: {}}

    # Loop over each possible value of the chosen attribute
    # Each value becomes a branch
    for value in data[best].unique():

      # Create subset
      subset = data[data[best] == value]

      # Handle empty subset
      if subset.empty:

        # Solve by predicting majority class of parent data (mode)
        tree[best][value] = data[target_column].mode()[0]

      # If the subset is not empty
      else:

        # if attribute best has already been used, cannot reuse
        remaining_attrs = [a for a in attributes if a != best]

        # Take a subset, remove used attribute and call build_tree again
        # Attach the returned subtree
        # Recursive function
        tree[best][value] = tree_induction(subset, remaining_attrs, target_column, min_samples)

    # Return the result
    return tree

Explanation:   
== The code ==   
This is the tree induction function. It recursively builds a decision tree by checking stop conditions, choosing the best attribute to split, splitting the data and repeating the process on each subset with the usage of entropy, information_gain and best_attribute functions created above.   
Step 1 and Step 2, we define the stopping condition. If all instances have the same class, we cannot split further as no uncertainty left as every row has the same label. Thus, we return the first label as all the result is same.  
If no attribute left or the attribute is smaller than the min_samples, we cannot split further to avoid overfitting but we need to decide the result immediately. Therefore we will use the mode() of the majority class. Both of them create leaf nodes but for different reasons.   
Step 3, we decide the best attribute to split the data in decision tree with the best_attribute function created just now.   
Step 4, we define a tree dictionary, and put the best as the key, the best will become the root of the tree to continue further split.   
Step 5, the for loop try every unique values one-by-one in each attribute, unique() means that we will not do the same value twice. For example if the support calls_bin value is 0, what is the target label, and when the value is 1, etc. They are the values.  
Step 6, we create subset to make it be tree branches.  
Step 7, For each data subset created by splitting on the selected attribute value, we first check whether the subset is empty. If the subset is empty, it means that there is no training instances corresponding to that attribute value. In this case, we will assign the majority class of the parent dataset as the result for the branch to avoid errors and make a reasonable predictions.  
If the subset is not empty, we remove the attribute that has been already used for splitting (best) from the attribute list to avoid redundancy in the decision tree. Then, we call the tree_induction function recursively on the subset with the remaining attributes to continue building the decision tree. This recursive process continues until one of the stopping conditions is met.  
Finally, this function will return the constructed tree that represented as a nested dictionary structure.  

== The outcome ==  
No outcome is shown as this is a model. The outcome will be shown if the model is used.

### 2.5 Train the Decision Tree

In [61]:
# Define the parameter for the tree_induction function
target = "Churn"
attributes = [col for col in train_df.columns if col != target]

# Create the decision tree model by calling tree_induction function
decision_tree = tree_induction(train_df, attributes, target, min_samples=200)

Explanation:  
== The code ==  
This algorithm learns patterns from the cleaned and binned training data. By calling the tree_induction function, the model determines the entire logical structure of the tree, including which attributes to split on, the optimal order of those splits, and the specific points where splitting should stop to prevent overfitting. Finally, we successfully create a trained model, the decision tree. Without this step, the classification function has no knowledge to reference when making predictions on new data.   

== The outcome ==  
No outcome is shown. This cell is mainly used to train model. The result is a stored nested dictionaty (decision_tree) that represents a set of hierarchical rules.

### 2.6 Classification function

In [62]:
# The function is using the trained tree
def classify(tree, instance):

  # If the tree is not a dictionary,
  # it means we reached a leaf node, the result has come out
  # We return the tree with this stopping condition
  if not isinstance(tree, dict):
    return tree

  # Get the first key of the dictionary
  attribute = next(iter(tree))

  # Get the corresponding value by calling the
  # dictionary with its key in the test instance
  value = instance[attribute]

  # Check if the value is available in the tree
  if value in tree[attribute]:

    # Move down the tree to the next node
    # Recursive function
    # Repeat the function until meet the stop condition
    return classify(tree[attribute][value], instance)

  else:

    # If the value is missing, return None
    return None

Explanation:  
== The code ==  
Classification is performed by traversing the decision tree from the root to a leaf node based on the attribute values of the input instance.  
The classification function is using the trained tree.  
Step 1 is the stopping condition. If the tree is not dictionary, means that we reach the leaf node, the result has come out, because the tree is build using dictionaries and the leaf nodes are class labels (the result). Therefore, we can return the leaf node (result) as the function is done.  
Step 2: get the attribute used at this node. It is the first key of the dictionary.  
Step 3: look up the value of that attribute in the dictionary instance.  
Step 4: find if the value is available in the tree dictionary value. If yes, call the classification function recursively to classify the data until it reached a leaf node. If the value is missing, return None. This is another stop condition.  

== The outcome ==   
No outcome is shown. The classification function is used to use the train data to do classification.  
If the classification function is used, it will return the class label (value) such as 1.0 or 0.0 as the final prediction.

The Decision Tree is constructed using a recursive tree induction algorithm. At each node, entropy and information gain are calculated for all candidate attributes. The attribute with the highest information gain is selected to split the data. This process repeats for each branch to create subtrees until a stopping condition is met (arrive the leaf node).

### 2.7 Predict function to test data

In [63]:
def predict(data, tree):
    # Convert DataFrame to dictionary
    instances = data.to_dict(orient='records')

    # Use classification function to use the trained model
    # Classify the model with each instance
    predictions = [classify(tree, inst) for inst in instances]

    # Put the result into predictions list
    data["Predicted_Churn"] = predictions

    return data["Predicted_Churn"]

Explanation:  
== The code ==  
From the data, we convert each row of record into dictionary and define it as instances.  
For each instance, use classify() to predict the result with tree_induction function.  
Put the result into the list named predictions.  

== The outcome ==  
A list of 0 and 1 value to show the result of Customer Churn type will be stored in an attribute called "Predicted Churn".

### 2.8 Evaluate the performance and outcome

### Train predictions analysis

In [64]:
train_predictions = predict(train_df, decision_tree)

# Print first 10 results
for i in range(30):
    # Access actual label from train_label Series and predicted label from train_df
    print(f"Actual: {train_label.iloc[i]} | Predicted: {train_predictions [i]}")

Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 0.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0
Actual: 1.0 | Predicted: 1.0

Explanation:  
== The code ==  
We do the prediction with predict(train_df, decision_tree). It means that we  train the training data with decision tree so we can compare the actual value (using train_label we defined before) with the prediction results (train_predictions).    

== The outcome ==  
We get a list of 1.0 in the actual value, but it is copied from the training data csv file label column. We can check the datafile, the first 30 lines target columns "Churn" are all 1.0.

### Test predictions analysis

In [65]:
predictions = predict(test_df, decision_tree)

# Initialise the correct variable
correct = 0

# Get the total by calculating the len of test_df
total = len(test_df)

# For each row in test_df
for i in range(total):
    if predictions [i] == test_label.iloc[i]:
        correct += 1

# Calculate the accuracy
accuracy = correct / total

# Print the accuracy
print(f"Accuracy: {accuracy} ({accuracy * 100:.4f} %)", "\n")

# Print first 10 results
for i in range(30):
    # Access actual label from train_label Series and predicted label from train_df
    print(f"Actual: {test_label.iloc[i]} | Predicted: {predictions [i]}")

Accuracy: 0.5654767452698294 (56.5477 %)

Actual: 1 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 1 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 1 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 0.0
Actual: 0 | Predicted: 0.0
Actual: 0 | Predicted: 1.0
Actual: 1 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 0.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 1 | Predicted: 1.0
Actual: 0 | Predicted: 1.0
Actual: 0 | Predicted: 0.0
Actual: 0 | Predicted: 0.0
Actual: 1 | Predicted: 1.0

Explanation:  
== The code ==  
Initialise the correct number as 0 to accumulate correct predicted data later. Get the total number of data by getting the length of test_data. For each data, if the predictions (predicted label) same with the test_label (test_df target column), it is correct, so the correct +1. Then, count the accuracy by dividing the correct value with total value. We can get the accuracy by decimal.
If we have 90 correct predictions with 100 test samples, the accuracy will be 90/100 = 0.9. That is 90%.

We do the prediction with predict(test_df, decision_tree). It means that we  train the testing data with decision tree so we can compare the actual value (using test_label we defined before) with the prediction results (predictions).    

== The outcome ==  
The accuracy will be shown.  
A list of actual label and predicted label can be observed.

### (3) Note. You can (but not must) use any reasonable pre-processing methods. You also can (but not must) use pre-pruned technique. If you do so, you must explain your reasons clearly.

### 3.1 Pre-processing Explanation

Pre-processing used:    
To handle missing values, we calculate the median and replace the missing values with median for numerical values. For categorical value, we use mode() to handle the missing value.    

For those unpredictive columns like CustomerID, we also drop it to increase the model efficiency and avoid redundancy while running the model.  

Equal-width frequency binning pd.(qcut). It is because continuous attributes cannot be directly used by from-scratch decision tree. The from-scratch decision tree only supports discrete values. Therefore, we use binning to transform numerical features like (Age or Total Spend) into discrete categories (like age_1, age_2, etc) .     

To avoid confusion and for easier implementation, we drop those original attributes after binning. For example, if we bin attribute "age", it will become "age_bin", then the attribute "age" is dropped.

### 3.2 Pre-pruning Explanation

Pre-pruning was applied by introducing a minimum sample threshold(min_samples) in tree_induction function.   
if len(attributes) == 0 or len(data) < min_samples:  
    return data[target_column].mode()[0]  
  If the number of instances at a node is below this threshold (min_samples), the splitting process stops and the majority class is returned. Otherwise, it will continue splitting until every single leaf is "pure" (Entropy = 0). Pre-pruning reduces overfitting noise data, while keeping the implementation simple and stable decision tree. Besides, it can effectively preserve computationally efficient.